[package]
name = "nash-codegen"
version = "0.1.0"
edition.workspace = true
description = "Nash specialization and lowering to Untyped Plutus Core"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
nash-ast = { path = "../nash-ast", version = "0.7.0" }
nash-region = { path = "../nash-region", version = "0.2.0" }
nash-can = { path = "../nash-can", version = "0.6.1" }
nash-solve = { path = "../nash-solve", version = "0.4.1" }
bumpalo.workspace = true
nash-ir = { path = "../nash-ir", version = "0.1.0" }
nash-plutus = { path = "../nash-plutus", version = "0.1.0" }
thiserror.workspace = true

[dev-dependencies]
nash-parse = { path = "../nash-parse", version = "0.5.1" }
nash-constrain = { path = "../nash-constrain", version = "0.4.1" }
nash-nitpick = { path = "../nash-nitpick", version = "0.2.0" }
indoc.workspace = true
insta.workspace = true
