[package]
name = "nash-nitpick"
version = "0.2.0"
edition.workspace = true
description = "Exhaustiveness and redundancy checking for Nash pattern matches"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bumpalo.workspace = true
hex.workspace = true
nash-ast = { path = "../nash-ast", version = "0.7.0" }
nash-region = { path = "../nash-region", version = "0.2.0" }

[dev-dependencies]
insta.workspace = true
