[package]
name = "nash-constrain"
version = "0.5.0"
edition.workspace = true
description = """
Shared union-find types, canonical type instantiation, and diagnostics \
for direct type inference.
"""
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bumpalo.workspace = true
nash-ast = { path = "../nash-ast", version = "0.7.1" }
nash-region = { path = "../nash-region", version = "0.3.0" }
