[package]
name = "nash-frontend"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bumpalo.workspace = true
url.workspace = true
nash-source = { path = "../nash-source" }
nash-region = { path = "../nash-region" }
nash-config = { path = "../nash-config" }
thiserror.workspace = true
