//! Late O1 cleanup and native application packing on named UPLC.
//!
//! Cleanup only shrinks terms; in particular it never duplicates a lambda body
//! or unfolds the multiple-use self applications generated by recursion encoding.
use nash_plutus::{arena::Arena, binder::Name, term::Term};
use std::{
    collections::{HashMap, HashSet},
    ptr,
};

type Uplc<'a> = &'a Term<'a, Name<'a>>;

/// Input must be closed and well-scoped; shadowed names are supported. Preserve
/// strict evaluation, traces and termination. Sharing runs before this pass:
/// forced builtin references and applied prefixes remain computations.
pub fn optimize<'a>(arena: &'a Arena, mut term: Uplc<'a>) -> Uplc<'a> {
    loop {
        let next = cleanup(arena, term);
        let next = rewrite(arena, next, |node| pack(arena, node));
        if ptr::eq(term, next) {
            return next;
        }
        term = next;
    }
}

fn value(term: Uplc<'_>) -> bool {
    matches!(
        term,
        Term::Var(_) | Term::Constant(_) | Term::Builtin(_) | Term::Lambda { .. } | Term::Delay(_)
    )
}

fn cleanup<'a>(arena: &'a Arena, term: Uplc<'a>) -> Uplc<'a> {
    let mut uses = HashMap::<usize, usize>::new();
    walk(term, |node| {
        if let Term::Var(name) = node {
            *uses.entry(name.unique()).or_default() += 1;
        }
    });
    rewrite(arena, term, |node| {
        if let Term::Force(Term::Delay(body)) = node {
            return Some(*body);
        }
        let Term::Apply {
            function: Term::Lambda { parameter, body },
            argument,
        } = node
        else {
            return None;
        };
        // This retains argument evaluation even for a failing computation.
        if matches!(body, Term::Var(name) if name.unique() == parameter.unique()) {
            return Some(*argument);
        }
        if !value(argument) {
            return None;
        }
        match uses.get(&parameter.unique()).copied().unwrap_or(0) {
            0 => Some(*body),
            1 if can_substitute(body, argument, parameter.unique()) => {
                Some(rewrite(arena, body, |node| match node {
                    Term::Var(name) if name.unique() == parameter.unique() => Some(*argument),
                    _ => None,
                }))
            }
            _ => None,
        }
    })
}

/// Named lowering is normally fresh, but public lowering also accepts shadowed
/// names. Reject any possible capture rather than assume global uniqueness.
/// Including bound argument names is conservative and avoids renaming or copying.
fn can_substitute(body: Uplc<'_>, argument: Uplc<'_>, parameter: usize) -> bool {
    let mut names = HashSet::new();
    names.insert(parameter);
    walk(argument, |node| {
        if let Term::Var(name) = node {
            names.insert(name.unique());
        }
    });
    let mut safe = true;
    walk(body, |node| {
        if let Term::Lambda { parameter, .. } = node {
            safe &= !names.contains(&parameter.unique());
        }
    });
    safe
}

fn pack<'a>(arena: &'a Arena, node: Uplc<'a>) -> Option<Uplc<'a>> {
    if !matches!(node, Term::Apply { .. }) {
        return None;
    }
    let mut head = node;
    let mut args = Vec::new();
    while let Term::Apply { function, argument } = head {
        args.push(*argument);
        head = function;
    }
    // A child may already have packed a prefix. Extend that same pack rather
    // than leave nested packs or expose a new opportunity on the next invocation.
    if let Term::Case {
        constr: Term::Constr { tag: 0, fields },
        branches: [function],
    } = head
    {
        args.extend(fields.iter().rev().copied());
        head = function;
    }
    // N Apply nodes become two nodes (Case + Constr). Three is the first arity
    // with fewer evaluator steps; this is not an optimizer resource limit.
    if args.len() < 3 || !value(head) || !args.iter().all(|arg| value(arg)) {
        return None;
    }
    args.reverse();
    Some(Term::case(
        arena,
        Term::constr(arena, 0, arena.alloc_slice_copy(&args)),
        arena.alloc_slice_copy(&[head]),
    ))
}

fn walk<'a>(root: Uplc<'a>, mut visit: impl FnMut(Uplc<'a>)) {
    let mut pending = vec![root];
    while let Some(node) = pending.pop() {
        visit(node);
        match node {
            Term::Apply { function, argument } => pending.extend([*argument, *function]),
            Term::Lambda { body, .. } | Term::Force(body) | Term::Delay(body) => pending.push(body),
            Term::Case { constr, branches } => {
                pending.extend(branches.iter().rev().copied());
                pending.push(constr);
            }
            Term::Constr { fields, .. } => pending.extend(fields.iter().rev().copied()),
            _ => {}
        }
    }
}

/// Iterative postorder rewriting, retaining every unchanged parent pointer.
fn rewrite<'a>(
    arena: &'a Arena,
    root: Uplc<'a>,
    mut rule: impl FnMut(Uplc<'a>) -> Option<Uplc<'a>>,
) -> Uplc<'a> {
    let mut pending = vec![(root, false, 0)];
    let mut results: Vec<Uplc<'a>> = Vec::new();
    while let Some((node, finish, start)) = pending.pop() {
        if !finish {
            pending.push((node, true, results.len()));
            match node {
                Term::Apply { function, argument } => {
                    pending.push((argument, false, 0));
                    pending.push((function, false, 0));
                }
                Term::Lambda { body, .. } | Term::Force(body) | Term::Delay(body) => {
                    pending.push((body, false, 0))
                }
                Term::Case { constr, branches } => {
                    pending.extend(branches.iter().rev().map(|branch| (*branch, false, 0)));
                    pending.push((constr, false, 0));
                }
                Term::Constr { fields, .. } => {
                    pending.extend(fields.iter().rev().map(|field| (*field, false, 0)))
                }
                _ => {}
            }
            continue;
        }
        let c = &results[start..];
        let mapped = match node {
            Term::Apply { function, argument }
                if !ptr::eq(*function, c[0]) || !ptr::eq(*argument, c[1]) =>
            {
                c[0].apply(arena, c[1])
            }
            Term::Lambda { parameter, body } if !ptr::eq(*body, c[0]) => {
                c[0].lambda(arena, parameter)
            }
            Term::Force(body) if !ptr::eq(*body, c[0]) => c[0].force(arena),
            Term::Delay(body) if !ptr::eq(*body, c[0]) => c[0].delay(arena),
            Term::Case { constr, branches }
                if !ptr::eq(*constr, c[0])
                    || !branches.iter().zip(&c[1..]).all(|(l, r)| ptr::eq(*l, *r)) =>
            {
                Term::case(arena, c[0], arena.alloc_slice_copy(&c[1..]))
            }
            Term::Constr { tag, fields } if !fields.iter().zip(c).all(|(l, r)| ptr::eq(*l, *r)) => {
                Term::constr(arena, *tag, arena.alloc_slice_copy(c))
            }
            _ => node,
        };
        let next = rule(mapped).unwrap_or(mapped);
        results.truncate(start);
        results.push(next);
    }
    results.pop().unwrap()
}

#[cfg(test)]
mod tests;
